package cii.sii.domain;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(753132795fd9bae392eeb9adfb7df6be)
 */
@org.kie.api.definition.type.Label(value = "Caso")
public class Caso extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Diferencia")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer diferencia;
    
    @org.kie.api.definition.type.Label(value = "Funcionario")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String funcionario;
    
    @org.kie.api.definition.type.Label(value = "Justificacion Contribuyente")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String justificacionContri;
    
    @org.kie.api.definition.type.Label(value = "Justificacion Fiscalizador")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String justificacionFisca;
    
    @org.kie.api.definition.type.Label(value = "Periodo")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String periodo;
    
    @org.kie.api.definition.type.Label(value = "RUT")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String rut;
    
    @org.kie.api.definition.type.Label(value = "Score")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer score;

    public Caso() {
    }

    public Caso(java.lang.String rut, java.lang.String periodo, java.lang.Integer diferencia, java.lang.Integer score, java.lang.String justificacionContri, java.lang.String funcionario, java.lang.String justificacionFisca) {
        this.rut = rut;
        this.periodo = periodo;
        this.diferencia = diferencia;
        this.score = score;
        this.justificacionContri = justificacionContri;
        this.funcionario = funcionario;
        this.justificacionFisca = justificacionFisca;
    }


    
    public java.lang.Integer getDiferencia() {
        return this.diferencia;
    }

    public void setDiferencia(java.lang.Integer diferencia) {
        this.diferencia = diferencia;
    }
    
    public java.lang.String getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(java.lang.String funcionario) {
        this.funcionario = funcionario;
    }
    
    public java.lang.String getJustificacionContri() {
        return this.justificacionContri;
    }

    public void setJustificacionContri(java.lang.String justificacionContri) {
        this.justificacionContri = justificacionContri;
    }
    
    public java.lang.String getJustificacionFisca() {
        return this.justificacionFisca;
    }

    public void setJustificacionFisca(java.lang.String justificacionFisca) {
        this.justificacionFisca = justificacionFisca;
    }
    
    public java.lang.String getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(java.lang.String periodo) {
        this.periodo = periodo;
    }
    
    public java.lang.String getRut() {
        return this.rut;
    }

    public void setRut(java.lang.String rut) {
        this.rut = rut;
    }
    
    public java.lang.Integer getScore() {
        return this.score;
    }

    public void setScore(java.lang.Integer score) {
        this.score = score;
    }
}