package cii.sii.domain;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(f06a87cd7bfc05965869b416e47983c7)
 */
@org.kie.api.definition.type.Label(value = "Contribuyente")
public class Contribuyente extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Email")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String email;
    
    @org.kie.api.definition.type.Label(value = "Rut")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String rut;

    public Contribuyente() {
    }

    public Contribuyente(java.lang.String rut, java.lang.String email) {
        this.rut = rut;
        this.email = email;
    }


    
    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public java.lang.String getRut() {
        return this.rut;
    }

    public void setRut(java.lang.String rut) {
        this.rut = rut;
    }
}