package cii.sii.domain;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(dfb92e999bc03b5bbee0a519f2c1f7d6)
 */
@org.kie.api.definition.type.Label(value = "Giro")
public class Giro  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "MontoDiferencia")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer montoDiferencia;
    
    @org.kie.api.definition.type.Label(value = "Rut")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String rut;

    public Giro() {
    }

    public Giro(java.lang.String rut, java.lang.Integer montoDiferencia) {
        this.rut = rut;
        this.montoDiferencia = montoDiferencia;
    }


    
    public java.lang.Integer getMontoDiferencia() {
        return this.montoDiferencia;
    }

    public void setMontoDiferencia(java.lang.Integer montoDiferencia) {
        this.montoDiferencia = montoDiferencia;
    }
    
    public java.lang.String getRut() {
        return this.rut;
    }

    public void setRut(java.lang.String rut) {
        this.rut = rut;
    }
}