package cii.sii.domain;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(c7f6902e6dbb1d8f4b849d74fe993e92)
 */
@org.kie.api.definition.type.Label(value = "Unidad")
public class Unidad extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Fiscalizadores")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.List<cii.sii.domain.Funcionario> fiscalizadores;
    
    @org.kie.api.definition.type.Label(value = "Nombre")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String nombre;

    public Unidad() {
    }

    public Unidad(java.lang.String nombre, java.util.List<cii.sii.domain.Funcionario> fiscalizadores) {
        this.nombre = nombre;
        this.fiscalizadores = fiscalizadores;
    }


    
    public java.util.List<cii.sii.domain.Funcionario> getFiscalizadores() {
        return this.fiscalizadores;
    }

    public void setFiscalizadores(java.util.List<cii.sii.domain.Funcionario> fiscalizadores) {
        this.fiscalizadores = fiscalizadores;
    }
    
    public java.lang.String getNombre() {
        return this.nombre;
    }

    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }
}